#!/bin/sh


#place in /etc/cron.daily and make executable with chmod +x  /etc/cron.daily/updatenc

sudo -u www-data php8.0 /var/www/nextcloud/updater/updater.phar --no-backup --no-interaction

sudo -u www-data php8.0 /var/www/nextcloud/occ status
sudo -u www-data php8.0 /var/www/nextcloud/occ -V

sudo -u www-data php8.0 /var/www/nextcloud/occ db:add-missing-primary-keys

sudo -u www-data php8.0 /var/www/nextcloud/occ db:add-missing-indices

sudo -u www-data php8.0 /var/www/nextcloud/occ db:add-missing-columns

sudo -u www-data php8.0 /var/www/nextcloud/occ db:convert-filecache-bigint

sudo -u www-data php8.0 /var/www/nextcloud/occ files:scan-app-data
sudo -u www-data php8.0 /var/www/nextcloud/occ app:update --all

sudo -u www-data php8.0 /var/www/nextcloud/occ upgrade

/usr/sbin/service php8.0-fpm restart
/usr/sbin/service nginx restart

sudo -u www-data php8.0 /var/www/nextcloud/occ -V
